import { useState, useEfect } from 'react';
import sanityClient, { urlFor } from '../../sanity';

import Image from 'next/image';
import Head from 'next/head';

import NavBarOrderScreen from '../../components/NavBarOrderScreen';
import MenuItems from '../../components/MenuItems';
import MainSection from '../../components/MainSection';
import Sidebar from '../../components/Sidebar';
import { fetchRestaurant } from '../../utils/fetchRestaurant';

import {
  ArrowLeftIcon,
  ChevronRightIcon,
  LocationMarkerIcon,
  QuestionMarkCircleIcon,
  StarIcon,
  MinusCircleIcon,
  PlusCircleIcon,
} from '@heroicons/react/24/solid';

const OrderScreen = ({ restaurant }) => {
  const {
    about_us,
    address,
    associatedMenuItemCategories,
    name,
    openingHours,
    image,
    short_description,
  } = restaurant;

  return (
    <div>
      <Head>
        <title>{name}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <NavBarOrderScreen />
      <main className='grid grid-cols-12'>
        <MainSection
          aboutUs={about_us}
          address={address}
          menuItemCategories={associatedMenuItemCategories}
          name={name}
          openingHours={openingHours}
          image={image}
          shortDescription={short_description}
        />
        {/* <div className='hidden col-span-3 lg:inline lg:max-w-7xl mx-auto h-[calc(100vh-36px)]'> */}
        <Sidebar />
      </main>
    </div>
  );
};

// TODO: Make sure to add top value after the nav gets implemented
// width: 340px;
// height: calc(100vh - 64px);
// flex-shrink: 0;
// position: fixed;
// top: 64px;
// right: 0px;

export default OrderScreen;

export const getStaticProps = async () => {
  const restaurant = await fetchRestaurant();
  return {
    props: { restaurant },
    revalidate: 10,
  };
};
