import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Navbar from '../components/Navbar';
import Slider from '../components/Slider';
import { fetchRestaurant } from '../utils/fetchRestaurant';
// import { fetchMenuCategories } from '../utils/fetchMenuCategories';
// import { useSelector, useDispatch } from 'react-redux';
// import { increment, decrement, selectValue } from '../slices/counterSlice';

const Home = ({ restaurant }) => {
  // const count = useSelector(selectValue);
  // const dispatch = useDispatch();
  return (
    <div className={styles.container}>
      <Head>
        <title>Sushiya Ramen</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <Slider />
    </div>
  );
};

export default Home;

export const getStaticProps = async () => {
  const restaurant = await fetchRestaurant();
  return {
    props: { restaurant },
    revalidate: 10,
  };
};
